image: Visual Studio 2019
build_script:
- ps: >-
    [xml]$doc = (Get-Content .\TMDbLib\TMDbLib.csproj)

    $version = $doc.Project.PropertyGroup.VersionPrefix

    Update-AppveyorBuild -Version "$version build $env:APPVEYOR_BUILD_NUMBER"
- ps: # Core
- ps: msbuild /t:Restore
- ps: # Build Library
- ps: msbuild /t:Build /p:Configuration=Release TMDbLib
- ps: # Library
- ps: msbuild /t:Pack /p:Configuration=Release /p:OutputPath=..\Nuget\ TMDbLib
- ps: # Test app
- ps: msbuild /t:Build /p:Configuration=Release TestApplication
- ps: # Tests
- ps: msbuild /t:Build /p:Configuration=Release TMDbLibTests
test: off
artifacts:
- path: Nuget\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: swSWyPAJ7RUvccBtHRrEAY7XXll/U2PkYNbyqrWTrQPTFsrf9LuDM/SJN3QM++T3
  on:
    branch: nuget