name: Nuget push (tag)

on: 
  push:
    tags:
    - 'v*'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
    # We do not need to fetch tags, as we're already at a tagged build - it should be available automatically

    - name: Setup .NET
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4
      with:
        dotnet-version: 7.0.x

    - name: Pack
      run: dotnet pack -c Release -o Build

    - name: ls
      run: ls -alh Build/
    
    - name: Nuget push (github)
      run: dotnet nuget push --no-symbols --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" Build/*.nupkg
      
    - name: Nuget push 
      run: dotnet nuget push --skip-duplicate -k ${{secrets.NUGET_APIKEY}} -s https://api.nuget.org/v3/index.json Build/*.nupkg
